@startuml
'https://plantuml.com/activity-diagram-beta

start
:画面表示;
:検索条件を未選択状態に設定;
while (遷移先画面が設定されているか)
:入力;
  switch (入力)
  case (検索条件が未選択かつqを入力)
    :遷移先画面にホーム画面を設定;
  case (検索条件が未選択かつ空文字を入力)
    :検索処理;
    :遷移先画面に一覧画面を設定;
  case (検索条件が未選択かつ0-9を入力)
    :検索条件を選択;
  case (検索条件が未選択かつ前述以外場合)
    :何も処理をしない（エラーメッセージが出せると良い）;
  case (検索条件を選択済み)
    :入力された値を選択した検索条件に設定;
    :検索条件を未選択状態に設定;
  endswitch
endwhile
:画面遷移;

stop

@enduml
